name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # Changed from 20.04 to latest
    steps:
      - name: Say Hello
        run: echo "Hello World!"
